# Data Split

In [6]:
import pandas as pd
import numpy as np
import os
import sys
module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)
import pickle as pickle

In [7]:
source_trace = pd.read_pickle("../../Data/Trace/source_trace_all_l.pkl")
target_trace = pd.read_pickle("../../Data/Trace/target_trace_all_l.pkl")

## Split

In [8]:
def split_data(data, ratio=[0.8, 0.1, 0.1], sort=True):
    data_size = data.shape[0]
    train_size = int(ratio[0] * data_size)
    val_size = int(ratio[1] * data_size)
    test_size = data_size - train_size - val_size
    if sort:
        data_sorted = data.sort_values(by='Start Time', ascending=True)
    else:
        data_sorted = data.sample(frac=1)
    data_train = data_sorted[:train_size]
    data_val = data_sorted[train_size: train_size+val_size]
    data_test = data_sorted[train_size+val_size:]
    return data_train, data_val, data_test

In [9]:
source_train, source_val, source_test = split_data(source_trace, sort=False)
target_train, target_val, target_test = split_data(target_trace, sort=False)

source_train.to_pickle("../../Data/Training/811split/source_train_random_all.pkl")
source_val.to_pickle("../../Data/Training/811split/source_val_random_all.pkl")
source_test.to_pickle("../../Data/Training/811split/source_test_random_all.pkl")

target_train.to_pickle("../../Data/Training/811split/target_train_random_all.pkl")
target_val.to_pickle("../../Data/Training/811split/target_val_random_all.pkl")
target_test.to_pickle("../../Data/Training/811split/target_test_random_all.pkl")

In [10]:
source_train, source_val, source_test = split_data(source_trace, ratio=[0.64,0.16,0.2], sort=False)
target_train, target_val, target_test = split_data(target_trace, ratio=[0.64,0.16,0.2], sort=False)

source_train.to_pickle("../../Data/Training/641620split/source_train_random_all.pkl")
source_val.to_pickle("../../Data/Training/641620split/source_val_random_all.pkl")
source_test.to_pickle("../../Data/Training/641620split/source_test_random_all.pkl")

target_train.to_pickle("../../Data/Training/641620split/target_train_random_all.pkl")
target_val.to_pickle("../../Data/Training/641620split/target_val_random_all.pkl")
target_test.to_pickle("../../Data/Training/641620split/target_test_random_all.pkl")

In [19]:
def split_data_alt(data, ratio=[0.8, 0.1, 0.1], sort=True):
    data_size = data.shape[0]
    train_size = int(ratio[0] * data_size)
    test_size = int(ratio[2] * data_size)
    if sort:
        data_sorted = data.sort_values(by='Start Time', ascending=True)
    else:
        data_sorted = data.sample(frac=1)
    data_test = data_sorted[-test_size:]
    
    data_rest = data_sorted[:-test_size]
    data_rest = data_rest.sample(frac=1)
    data_train = data_rest[:train_size]
    data_val = data_rest[train_size:]
    return data_train, data_val, data_test

In [20]:
source_train, source_val, source_test = split_data_alt(source_trace)
target_train, target_val, target_test = split_data_alt(target_trace)

source_train.to_pickle("../../Data/Training/811split/source_train_alt.pkl")
source_val.to_pickle("../../Data/Training/811split/source_val_alt.pkl")
source_test.to_pickle("../../Data/Training/811split/source_test_alt.pkl")

target_train.to_pickle("../../Data/Training/811split/target_train_alt.pkl")
target_val.to_pickle("../../Data/Training/811split/target_val_alt.pkl")
target_test.to_pickle("../../Data/Training/811split/target_test_alt.pkl")

In [22]:
source_train, source_val, source_test = split_data_alt(source_trace, ratio=[0.64,0.16,0.2])
target_train, target_val, target_test = split_data_alt(target_trace, ratio=[0.64,0.16,0.2])

source_train.to_pickle("../../Data/Training/641620split/source_train_alt.pkl")
source_val.to_pickle("../../Data/Training/641620split/source_val_alt.pkl")
source_test.to_pickle("../../Data/Training/641620split/source_test_alt.pkl")

target_train.to_pickle("../../Data/Training/641620split/target_train_alt.pkl")
target_val.to_pickle("../../Data/Training/641620split/target_val_alt.pkl")
target_test.to_pickle("../../Data/Training/641620split/target_test_alt.pkl")

In [18]:
target_test

,Event_Name,Timestamp,Purchase_Order_ID,Start Time,CaseDuration,CaseInterval,CaseLapse,OverallCriteria,Label
Case_ID,,,,,,,,,
4508048286,"[Create Purchase Order Item, Create Purchase O...","[2018-08-09T12:28:00.000000000, 2018-08-09T12:...","[4508048286_00010, 4508048286_00020, 450804828...",2018-08-09 12:28:00,112235.0,"[0.0, 0.0, 32371.0, 3731.0, 2.0, 587.0, 656.0,...","[0.0, 0.0, 32371.0, 36102.0, 36104.0, 36691.0,...",145696.0,1
4508048287,"[Create Purchase Order Item, Vendor creates in...","[2018-08-09T12:29:00.000000000, 2018-10-11T23:...","[4508048287_00010, 4508048287_00010, 450804828...",2018-08-09 12:29:00,139515.0,"[0.0, 91410.0, 6429.0, 2962.0, 38714.0]","[0.0, 91410.0, 97839.0, 100801.0, 139515.0]",145696.0,1
4508048288,"[Create Purchase Order Item, Change Quantity, ...","[2018-08-09T12:30:00.000000000, 2018-09-21T13:...","[4508048288_00010, 4508048288_00010, 450804828...",2018-08-09 12:30:00,98130.0,"[0.0, 61956.0, 653.0, 6160.0, 1979.0, 27382.0]","[0.0, 61956.0, 62609.0, 68769.0, 70748.0, 9813...",145696.0,1
4508048289,"[Create Purchase Order Item, Change Quantity, ...","[2018-08-09T12:32:00.000000000, 2018-10-08T14:...","[4508048289_00010, 4508048289_00010, 450804828...",2018-08-09 12:32:00,139512.0,"[0.0, 86515.0, 572.0, 868.0, 572.0, 907.0, 850...","[0.0, 86515.0, 87087.0, 87955.0, 88527.0, 8943...",145696.0,1
4508048290,"[Create Purchase Order Item, Vendor creates in...","[2018-08-09T12:34:00.000000000, 2018-09-21T23:...","[4508048290_00010, 4508048290_00010, 450804829...",2018-08-09 12:34:00,98126.0,"[0.0, 62605.0, 9473.0, 3866.0, 1807.0, 20375.0]","[0.0, 62605.0, 72078.0, 75944.0, 77751.0, 9812...",145696.0,1
...,...,...,...,...,...,...,...,...,...
4508060518,"[Create Purchase Requisition Item, Create Purc...","[2018-10-09T00:00:00.000000000, 2018-10-09T10:...","[4508060518_00010, 4508060518_00010, 450806051...",2018-10-09 00:00:00,85508.0,"[0.0, 646.0, 50.0, 3623.0, 599.0, 47883.0, 315...","[0.0, 646.0, 696.0, 4319.0, 4918.0, 52801.0, 8...",145696.0,1
4508060753,"[Create Purchase Requisition Item, Create Purc...","[2018-10-09T00:00:00.000000000, 2018-10-09T00:...","[4508060753_00010, 4508060753_00020, 450806075...",2018-10-09 00:00:00,9254.0,"[0.0, 0.0, 1999.0, 0.0, 64.0, 0.0, 7191.0, 0.0]","[0.0, 0.0, 1999.0, 1999.0, 2063.0, 2063.0, 925...",145696.0,1
4508060392,"[Record Service Entry Sheet, Record Goods Rece...","[2018-10-09T02:02:00.000000000, 2018-10-09T02:...","[4508060392_00001, 4508060392_00001, 450806039...",2018-10-09 02:02:00,19.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",145696.0,1
4508060393,"[Create Purchase Order Item, Record Goods Rece...","[2018-10-09T02:03:00.000000000, 2018-10-09T02:...","[4508060393_00001, 4508060393_00001, 450806039...",2018-10-09 02:03:00,1.0,"[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",145696.0,1
4508060394,"[Record Service Entry Sheet, Record Service En...","[2018-10-09T02:04:00.000000000, 2018-10-09T02:...","[4508060394_00001, 4508060394_00001, 450806039...",2018-10-09 02:04:00,3.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",145696.0,1